Ques 1. Create a vector with values ranging from 10 to 49#

In [1]:
import numpy as np
v = np.arange(10,49)
print("Original vector:")
print(v)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#Ques 2. Reverse a vector (first element becomes last)¶

In [2]:
import numpy as np

In [5]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#Ques 3.Create a 3x3 identity matrix

In [7]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Ques 4. Create a 10x10 array with random values and find the minimum and maximum values

In [8]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.38708773 0.96440488 0.83874636 0.52672585 0.11725494 0.39464268
  0.22783743 0.48984327 0.84724515 0.89496669]
 [0.34153673 0.20125598 0.34808378 0.55922656 0.16455346 0.06117576
  0.66152655 0.56243458 0.87895898 0.59585612]
 [0.42419818 0.89018717 0.88056884 0.95217155 0.79066407 0.16618283
  0.99339456 0.78015839 0.3141937  0.55532425]
 [0.97276329 0.19658552 0.20983919 0.23406134 0.93957632 0.49033099
  0.78387085 0.29734748 0.43103173 0.005074  ]
 [0.58518415 0.24774912 0.01722797 0.64615332 0.61130484 0.42489485
  0.35265592 0.28391725 0.18185965 0.4925932 ]
 [0.32763511 0.20803916 0.9054493  0.07400959 0.30310582 0.68387532
  0.20551955 0.16969008 0.40271462 0.76390225]
 [0.06503719 0.50158294 0.16201824 0.71307484 0.96152872 0.23262905
  0.3388612  0.71248174 0.34889746 0.94881663]
 [0.31537313 0.97917871 0.79208028 0.75318771 0.71206722 0.73759644
  0.52943467 0.24786954 0.31847654 0.74982532]
 [0.1048633  0.58636254 0.55405887 0.24331743 0.23226524 0.88194

#Ques 6.How to sum a small array faster than np.sum?


In [12]:

import numpy as np

# 1D array
arr = [20, 2, .2, 10, 4]

print("\nSum of arr : ", np.sum(arr))

print("Sum of arr(uint8) : ", np.sum(arr, dtype = np.uint8))
print("Sum of arr(float32) : ", np.sum(arr, dtype = np.float32))

print ("\nIs np.sum(arr).dtype == np.uint : ",
np.sum(arr).dtype == np.uint)

print ("Is np.sum(arr).dtype == np.float : ",
np.sum(arr).dtype == np.float)



Sum of arr :  36.2
Sum of arr(uint8) :  36
Sum of arr(float32) :  36.2

Is np.sum(arr).dtype == np.uint :  False
Is np.sum(arr).dtype == np.float :  True


#Ques 7.How to find the closest value (to a given scalar) in a vector?¶